---
title: "DAS GROUP 8 PROJECT "
author: "Constantinos Anastasiou, Lin Lin, Yuang Tian, Yutong WU, Shengyuan Xia"
number-sections: true
format: 
  html:
    embed-resources: true
    code-tools: true
  pdf: default
editor_options: 
  chunk_output_type: console
execute:
  echo: false
  eval: true
  warning: false
  message: false
---

```{r}
#| label: libraries
library(ggplot2)
library(tidyverse)
library(gt)
library(patchwork)
library(gridExtra)
library(moderndive)


data <- read.csv("dataset08.csv")
data
films <- na.omit(data)


films
```

```{r}
#| label: data
data <- read.csv("dataset08.csv")
dataNEW <- na.omit(data)
colnames(dataNEW) <- c("FILM ID", "YEAR RELEASED", "LENGTH", "BUDGET" , "VOTES" ,"GENRE" , "RATING") 

```

# Introduction {#sec-Intro}

# Exploratory Data Analysis {#sec-EDA}

# Formal Data Analysis {#sec-FDA}

```{r}

#WE CONVERT RATING TO BINARY VARIABLE

films$GREAT <- ifelse(films$rating > 7 , 1 ,0)
films

#FIT GLM
#NOTE WE ARE NOT INCLUDING film id as it obviously doesn't have an effect on the film's rating
glm_model <- glm(GREAT ~ film_id + year + length + budget + votes + genre , data = films , family = binomial)
summary(glm_model)
```
